[package]
name = "vrft_udp_rcv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
api = { path = "../vrft_d/api" }
log = "0.4"
env_logger = "0.11"
