[package]
name = "sranipal_module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
log = "0.4"
libloading = "0.8"
glam = "0.24"

[dependencies.api]
path = "../../vrft_d/api"
