[package]
name = "netclr"
version = "0.1.0"
edition = "2021"

[dependencies]
netcorehost = "0.20"
api = { path = "../api" }
glam = "0.24"
anyhow = "1.0"
log = "0.4"
thiserror = "1.0"
once_cell = "1.18"

[dev-dependencies]
env_logger = "0.10"