[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.31"
anyhow = "1.0"
api = { path = "../api" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"

[features]
xtralog = []